apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260522-145241-avjgnvxz3zah-service
spec:
  selector:
    app: enterprise-system-20260522-145241-avjgnvxz3zah
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
